# Site settings
title: CSS Ruler
description: "Explore CSS lengths."
baseurl: "/css-ruler"
url: "http://katydecorah.com"
permalink: pretty

# Build settings
markdown: kramdown
port: 4000
host: 127.0.0.1

gems:
- jemoji
- jekyll-sitemap

sass:
  style: :compressed

jquery: 1.11.2
angularjs: 1.4.1
