# Site settings
title: CSS Ruler
description: "Explore CSS lengths."
baseurl: "/css-ruler"
url: "http://katydecorah.com"
permalink: pretty

# Build settings
markdown: kramdown

gems:
- jemoji
- jekyll-sitemap

sass:
  style: :compressed

jquery: 1.11.2
angularjs: 1.3.8
